tasks:
- install:
- ceph:
- rgw:
    storage classes: LUKEWARM, FROZEN
    client.0:
      port: 8000
    client.1:
      port: 8001
    client.2:
      port: 8002
- rgw-cloudtier:
    client.0:
      cloud_storage_class: cloudtier-client0
      cloud_tier_type: cloud-s3-glacier
      cloud_client: client.1
      cloud_regular_storage_class: lukewarm
      cloud_target_storage_class: frozen
      cloud_retain_head_object: "true"
      cloud_target_path: "teuthology-client0"
      cloud_allow_read_through: "true"
      cloud_read_through_restore_days: "1"
      cloudtier_user:
        # cloud-user creds to be created on cloud-client
        cloud_secret: "abcefgh"
        cloud_access_key: "12345678"
      cloud_s3_glacier:
        cloud_s3_glacier_restore_tier_type: "Expedited"
    client.1:
      cloud_storage_class: cloudtier-client1
      cloud_tier_type: cloud-s3
      cloud_client: client.2
      cloud_regular_storage_class: lukewarm
      cloud_target_storage_class: frozen
      cloud_retain_head_object: "true"
      cloud_target_path: "teuthology-client1"
      cloud_allow_read_through: "true"
      cloud_read_through_restore_days: "1"
      cloudtier_user:
        # cloud-user creds to be created on cloud-client
        cloud_secret: "abcefghi"
        cloud_access_key: "123456789"
- tox: [client.0 , client.1]
- s3tests:
    client.0:
      rgw_server: client.0
      storage classes: LUKEWARM, FROZEN
      extra_attrs: ["cloud_restore"]
      lc_debug_interval: 10
      rgw_restore_debug_interval: 20
      lifecycle_tests: True
      cloudtier_tests: True
      access_key: "client0accesskey"
      secret_key: "client0secretkey"
      email: "client.0@test.com"
    client.1:
      rgw_server: client.1
      storage classes: LUKEWARM, FROZEN
      extra_attrs: ["cloud_restore"]
      lc_debug_interval: 10
      rgw_restore_debug_interval: 20
      lifecycle_tests: True
      cloudtier_tests: True
      access_key: "client1accesskey"
      secret_key: "client1secretkey"
      email: "client.1@test.com"
